version: '3.8'


services:

  btc:
    build: ./
    command: poetry run python main.py
    env_file: ./.env
    restart: always
    networks:
      - GLOBAL_NETWORK


networks:
  GLOBAL_NETWORK:
    external: true
